export const STAFF_DESIGNATIONS = [
  'Business Partner',
  'Center Manager',
  'Client Relationship Executive',
  'Client Relationship Manager',
  'Club Manager',
  'Diet Coach',
  'Director',
  'Fitness Coach',
  'Fitness Manager',
  'Fitness Trainer',
  'Front Desk',
  'General Trainer',
  'House Keeping',
  'Nutritionist',
  'Owner',
  'Personal Trainer',
  'Physiotherapist',
  'Sales Executive',
  'Sales Manager',
  'Yoga Instructor',
  'Zumba Instructor',
  'Receptionist',
  'Accountant',
  'Other',
];

export const STAFF_ADMIN_RIGHTS = [
  'Master Admin',
  'Admin',
  'Finance',
  'Training',
  'Sales',
  'Client Management',
  'Customer Service',
  'Housekeeping',
];
