// <auto-generated />
using AbsoluteFitManagement.Infrastructure.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AbsoluteFitManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AbsoluteFitManagementDbContext))]
    [Migration("20260426212603_AddQuickAddMenuItems")]
    partial class AddQuickAddMenuItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
